# Generated by Django 5.2.17 on 2026-08-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_condition_and_warranty_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_connectivity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_variants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_warranty_provider',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='proposed_warranty_requires_seal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='supplier_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='connectivity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_provider',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_requires_seal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_updates', to='catalog.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('source_text', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.supplier')),
            ],
            options={
                'ordering': ('purchase_price', '-last_seen_at'),
                'constraints': [models.UniqueConstraint(fields=('product', 'supplier', 'supplier_sku'), name='unique_product_supplier_sku')],
            },
        ),
    ]
