# Generated by Django 5.2.17 on 2026-08-19 22:46

from django.db import migrations


def apply_warranty_rules(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.select_related('condition'):
        identity = f'{product.brand} {product.model} {product.name}'.casefold()
        condition = product.condition.name.casefold().strip()
        months = provider = None
        if any(term in identity for term in ('xiaomi', 'redmi', 'poco')):
            months, provider = 6, 'AstroTech'
        elif any(term in identity for term in ('apple', 'iphone')):
            if condition == 'novo/lacrado':
                months, provider = 12, 'Fabricante'
            elif condition == 'seminovo premium':
                months, provider = 6, 'AstroTech'
            elif condition == 'seminovo':
                months, provider = 4, 'AstroTech'
        if months is not None:
            Product.objects.filter(pk=product.pk).update(
                warranty_months=months,
                warranty_provider=provider,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_price'),
    ]

    operations = [migrations.RunPython(apply_warranty_rules, migrations.RunPython.noop)]
